version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\glintercept
image:
- Visual Studio 2015
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- Win32
- x64
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set garch=
- if "%platform%"=="x64" ( set garch= Win64)
- echo %garch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%garch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%garch%" )
- echo %generator%

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%
build:
  project: c:\projects\glintercept\build\GLIntercept.sln
  verbosity: minimal
  parallel: true
only_commits:
  files:
    - src\Workspaces\CMakeLists.txt
    - appveyor.yml

